[versions]

glideVersion = "4.14.2"
lifecycleVersion = "2.5.1"

[libraries]

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
lifecycle_runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleVersion" }
lifecycle_viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleVersion" }
lifecycle_livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleVersion" }

[bundles]

lifecycle = ["lifecycle_runtime", "lifecycle_viewmodel", "lifecycle_livedata"]

