object Libs {
    const val androidCore = "androidx.core:core-ktx:${Version.androidCoreVersion}"
    const val material = "com.google.android.material:material:${Version.materialVersion}"
    const val appCompat = "androidx.appcompat:appcompat:${Version.appCompatVersion}"
    const val constraint = "androidx.constraintlayout:constraintlayout:${Version.constraintVersion}"
    const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib:${Version.kotlinVersion}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Version.retrofitVersion}"
    const val okHttp = "com.squareup.okhttp3:okhttp:${Version.okHttpVersion}"
    const val gson = "com.squareup.retrofit2:converter-gson:${Version.gsonVersion}"
    const val coroutine = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Version.coroutineVersion}"
    const val dagger = "com.google.dagger:dagger-android:${Version.daggerVersion}"
    const val daggerSupport = "com.google.dagger:dagger-android-support:${Version.daggerVersion}"
    const val daggerAnnotationProcessor = "com.google.dagger:dagger-android-processor:${Version.daggerVersion}"
    const val fragment = "androidx.fragment:fragment-ktx:${Version.fragmentVersion}"
}
